apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
type: Opaque
stringData:
  # Use one Azure auth style:
  AZURE_STORAGE_CONNECTION_STRING: CHANGE_ME
  # AZURE_STORAGE_ACCOUNT: CHANGE_ME
  # AZURE_STORAGE_KEY: CHANGE_ME
  # AZURE_STORAGE_SAS_TOKEN: CHANGE_ME

  MINIO_ACCESS_KEY: CHANGE_ME
  MINIO_SECRET_KEY: CHANGE_ME
  PGPASSWORD: CHANGE_ME
